version: "3.1"

services: 
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  api: 
    build: ../Passenger
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - '5000:5000'